# Usa uma imagem base do Node.js
FROM node:14

# Define o diretório de trabalho no contêiner
WORKDIR /usr/src/app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Comando para iniciar o servidor com nodemon
CMD ["npm", "run", "dev"]
